// sample github url response

const res = {
    "login": "harsh3dev",
    "id": 121597877,
    "node_id": "U_kgDOBz9vtQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/121597877?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/harsh3dev",
    "html_url": "https://github.com/harsh3dev",
    "followers_url": "https://api.github.com/users/harsh3dev/followers",
    "following_url": "https://api.github.com/users/harsh3dev/following{/other_user}",
    "gists_url": "https://api.github.com/users/harsh3dev/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/harsh3dev/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/harsh3dev/subscriptions",
    "organizations_url": "https://api.github.com/users/harsh3dev/orgs",
    "repos_url": "https://api.github.com/users/harsh3dev/repos",
    "events_url": "https://api.github.com/users/harsh3dev/events{/privacy}",
    "received_events_url": "https://api.github.com/users/harsh3dev/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Harsh Pandey",
    "company": "Institute of Engineering and Management, Kolkata",
    "blog": "",
    "location": "India",
    "email": null,
    "hireable": null,
    "bio": "AI and Web Development",
    "twitter_username": "harsh3dev",
    "public_repos": 27,
    "public_gists": 0,
    "followers": 4,
    "following": 12,
    "created_at": "2022-12-29T05:44:35Z",
    "updated_at": "2024-07-19T06:12:46Z"
    }