"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider"
import { Provider } from "react-redux";
import { makeStore } from "@/redux/store";


const inter = Inter({ subsets: ["latin"] });

 export const metadata: Metadata = {
  title: "Dev Matchups",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const store=makeStore();
  return (
    <Provider store={store}>
    <html lang="en">
      <body className={`{inter.className} `}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
      </body>
    </html>
    </Provider>
  );
}
