

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider"
import StoreProvider from "./StoreProvider";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "./provider";



const inter = Inter({ subsets: ["latin"] });

 export const metadata: Metadata = {
  title: "Dev Matchups",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`{inter.className} `}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <NextAuthProvider>
            <StoreProvider>
            {children}
            </StoreProvider>
            </NextAuthProvider>
            <Toaster />
          </ThemeProvider>
      </body>
    </html>
  );
}
